name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

#Controls when the workflow will run
on: 
  push:
      branches: [ main ] 
#[push]
#Trigger the workflow for push events but only for the main branch
#  push: 
#    branches[main]

#Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch: 

jobs:
  Explore-GitHub-Actions:
    runs-on: 
      - self-hosted
      - arc-runner-repo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      #- name: Build docker
      #  run: |
      #     docker build  -f backend/Dockerfile -t node/runner backend   
      - name: Check java version
        run: |
          java -version
      - name: Test maven version
        run: |
          mvn -version          